FROM eclipse-temurin
LABEL maintainer ='balaji71701@gmail.com'
WORKDIR /app
COPY target/ems-backend-0.0.1-SNAPSHOT.jar /app/ems-backend-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","ems-backend-0.0.1-SNAPSHOT.jar"]